### ISSUE TITLE
An issue when creating a new extension related to bbcode.

### ISSUE THREAD

**Issue by Aurorum-Studio** [s9e/TextFormatter#202]
Hi, I'm creating a new extension about bbcode-iframe (I know that iframe is not a welcoming attribute to many people, but I really need it😅), I tried to add the following part to `zerosonesfun/iframe`, so some of the attributes could work better, with more customized features, 
```php
return [ 
  (new Extend\Frontend('forum'))
  ->css(__DIR__.'/less/forum.less'),
    (new Extend\Formatter)
    ->configure(function (Configurator $config) {
         $config->BBCodes->addCustom(
           '[iframe={URL} width={WID} height={HID} frameborder={FID} marginwidth={MWI} marginheight={MHI} vspace={VSI} hspace={HSI} allowtransparency={AID} scrolling={SID} allowfullscreen={ALI}]',
           '<div class="iframe" style="--aspect-ratio: 16/9;">
           <iframe 
             src="{URL}"
             width="{WID}"
             height="{HID}"
             frameborder="{FID}"
             marginwidth="{MWI}"
             marginheight="{MHI}" 
             vspace="{VSI}"
             hspace="{HSI}"
             allowtransparency="{AID}"
             scrolling="{SID}"
             allowfullscreen="{ALI}"
           >
           </iframe>
         </div>'
        );
    })
];
```
but the flarum occurs an error, and the error-log is shown below:, how could I fix this😅
```
[2022-08-31 05:47:57] flarum.ERROR: InvalidArgumentException: Unknown attribute filter 'Wid' in /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/s9e/text-formatter/src/Configurator/Collections/AttributeFilterCollection.php:59
Stack trace:
#0 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/s9e/text-formatter/src/Configurator/Collections/AttributeFilterCollection.php(29): s9e\TextFormatter\Configurator\Collections\AttributeFilterCollection::getDefaultFilter()
#1 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/s9e/text-formatter/src/Plugins/BBCodes/Configurator/BBCodeMonkey.php(734): s9e\TextFormatter\Configurator\Collections\AttributeFilterCollection->get()
#2 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/s9e/text-formatter/src/Plugins/BBCodes/Configurator/BBCodeMonkey.php(403): s9e\TextFormatter\Plugins\BBCodes\Configurator\BBCodeMonkey->generateAttribute()
#3 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/s9e/text-formatter/src/Plugins/BBCodes/Configurator/BBCodeMonkey.php(301): s9e\TextFormatter\Plugins\BBCodes\Configurator\BBCodeMonkey->addAttributes()
#4 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/s9e/text-formatter/src/Plugins/BBCodes/Configurator/BBCodeMonkey.php(110): s9e\TextFormatter\Plugins\BBCodes\Configurator\BBCodeMonkey->parse()
#5 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/s9e/text-formatter/src/Plugins/BBCodes/Configurator.php(104): s9e\TextFormatter\Plugins\BBCodes\Configurator\BBCodeMonkey->create()
#6 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/zerosonesfun/flarum-bbcode-iframe/extend.php(24): s9e\TextFormatter\Plugins\BBCodes\Configurator->addCustom()
#7 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Formatter/Formatter.php(164): Flarum\Extension\Extension->ZerosOnesFun\Iframe\{closure}()
#8 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Formatter/Formatter.php(196): Flarum\Formatter\Formatter->getConfigurator()
#9 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/illuminate/cache/Repository.php(426): Flarum\Formatter\Formatter->Flarum\Formatter\{closure}()
#10 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Formatter/Formatter.php(197): Illuminate\Cache\Repository->rememberForever()
#11 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Formatter/Formatter.php(240): Flarum\Formatter\Formatter->getComponent()
#12 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Forum/ForumServiceProvider.php(112): Flarum\Formatter\Formatter->getJs()
#13 [internal function]: Flarum\Forum\ForumServiceProvider->Flarum\Forum\{closure}()
#14 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Frontend/Compiler/Source/StringSource.php(38): call_user_func()
#15 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Frontend/Compiler/Source/StringSource.php(49): Flarum\Frontend\Compiler\Source\StringSource->getContent()
#16 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Frontend/Compiler/RevisionCompiler.php(179): Flarum\Frontend\Compiler\Source\StringSource->getCacheDifferentiator()
#17 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Frontend/Compiler/RevisionCompiler.php(70): Flarum\Frontend\Compiler\RevisionCompiler->calculateRevision()
#18 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Frontend/Compiler/RevisionCompiler.php(110): Flarum\Frontend\Compiler\RevisionCompiler->commit()
#19 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Frontend/Content/Assets.php(79): Flarum\Frontend\Compiler\RevisionCompiler->getUrl()
#20 [internal function]: Flarum\Frontend\Content\Assets->Flarum\Frontend\Content\{closure}()
#21 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Frontend/Content/Assets.php(78): array_map()
#22 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Frontend/Content/Assets.php(55): Flarum\Frontend\Content\Assets->getUrls()
#23 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Frontend/Frontend.php(62): Flarum\Frontend\Content\Assets->__invoke()
#24 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Frontend/Frontend.php(54): Flarum\Frontend\Frontend->populate()
#25 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Frontend/Controller.php(32): Flarum\Frontend\Frontend->document()
#26 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Http/RouteHandlerFactory.php(41): Flarum\Frontend\Controller->handle()
#27 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#28 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ExecuteRoute->process()
#29 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/kilowhat/flarum-ext-audit-free/src/Middlewares/SetLoggerActor.php(28): Laminas\Stratigility\Next->handle()
#30 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/Next.php(51): Kilowhat\Audit\Middlewares\SetLoggerActor->process()
#31 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/malago/flarum-achievements/src/Middlewares/MiddlewarePosted.php(27): Laminas\Stratigility\Next->handle()
#32 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/Next.php(51): Malago\Achievements\Middlewares\MiddlewarePosted->process()
#33 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Http/Middleware/ContentTypeOptionsHeader.php(21): Laminas\Stratigility\Next->handle()
#34 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ContentTypeOptionsHeader->process()
#35 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Http/Middleware/ReferrerPolicyHeader.php(30): Laminas\Stratigility\Next->handle()
#36 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ReferrerPolicyHeader->process()
#37 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Http/Middleware/FlarumPromotionHeader.php(30): Laminas\Stratigility\Next->handle()
#38 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\FlarumPromotionHeader->process()
#39 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Http/Middleware/ShareErrorsFromSession.php(57): Laminas\Stratigility\Next->handle()
#40 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ShareErrorsFromSession->process()
#41 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(36): Laminas\Stratigility\Next->handle()
#42 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\CheckCsrfToken->process()
#43 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(67): Laminas\Stratigility\Next->handle()
#44 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ResolveRoute->process()
#45 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle()
#46 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\SetLocale->process()
#47 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(31): Laminas\Stratigility\Next->handle()
#48 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\AuthenticateWithSession->process()
#49 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Laminas\Stratigility\Next->handle()
#50 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\RememberFromCookie->process()
#51 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#52 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\StartSession->process()
#53 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Http/Middleware/CollectGarbage.php(46): Laminas\Stratigility\Next->handle()
#54 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\CollectGarbage->process()
#55 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#56 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ParseJsonBody->process()
#57 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#58 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\HandleErrors->process()
#59 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Http/Middleware/InjectActorReference.php(25): Laminas\Stratigility\Next->handle()
#60 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\InjectActorReference->process()
#61 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#62 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#63 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\RequestHandler->process()
#64 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/middlewares/base-path-router/src/BasePathRouter.php(101): Laminas\Stratigility\Next->handle()
#65 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\BasePathRouter->process()
#66 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(36): Laminas\Stratigility\Next->handle()
#67 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/Next.php(51): Laminas\Stratigility\Middleware\OriginalMessages->process()
#68 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/middlewares/base-path/src/BasePath.php(73): Laminas\Stratigility\Next->handle()
#69 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\BasePath->process()
#70 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Http/Middleware/ProcessIp.php(24): Laminas\Stratigility\Next->handle()
#71 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ProcessIp->process()
#72 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#73 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(65): Laminas\Stratigility\MiddlewarePipe->process()
#74 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle()
#75 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/vendor/flarum/core/src/Http/Server.php(44): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#76 /home/r93mrt078ftd/public_html/dl.aurorum.co/dl/public/index.php(26): Flarum\Http\Server->listen()
#77 {main}
```

**Comment by JoshyPHP** [comment]
When you use `{URL}` it means you expect a URL. Tokens map directly to attribute filters. If you expect a number, you can use `{NUMBER}`, `{UINT}`, or one of the other numeric filters. You can give a number to each token to differentiate them, e.g. `{UINT1}`, `{UINT2}`, or you can use the attribute name in the template. For example: `<iframe style="max-width:{@width}">`

https://s9etextformatter.readthedocs.io/Filters/Built-in_filters/
