### ISSUE TITLE
Compatibility with `flarum/mentions^1.6.3`

### ISSUE THREAD

**Issue by n0099** [s9e/TextFormatter#214]
Posting any reply contains mentions with post id such as `@"n0099"#p1` will cause
```log
flarum.ERROR: ArgumentCountError: Too few arguments to function Flarum\Mentions\ConfigureMentions::addPostId(), 1 passed and exactly 2 expected in vendor/flarum/mentions/src/ConfigureMentions.php:128
Stack trace:
#0 [internal function]: Flarum\Mentions\ConfigureMentions::addPostId()
#1 vendor/s9e/text-formatter/src/Parser/FilterProcessing.php(209): call_user_func_array()
#2 vendor/s9e/text-formatter/src/Parser/FilterProcessing.php(130): s9e\TextFormatter\Parser\FilterProcessing::executeFilter()
#3 vendor/s9e/text-formatter/src/Parser.php(1441): s9e\TextFormatter\Parser\FilterProcessing::filterTag()
#4 vendor/s9e/text-formatter/src/Parser.php(1396): s9e\TextFormatter\Parser->processStartTag()
#5 vendor/s9e/text-formatter/src/Parser.php(1297): s9e\TextFormatter\Parser->processCurrentTag()
#6 vendor/s9e/text-formatter/src/Parser.php(345): s9e\TextFormatter\Parser->processTags()
#7 vendor/flarum/core/src/Formatter/Formatter.php(105): s9e\TextFormatter\Parser->parse()
#8 vendor/flarum/core/src/Post/CommentPost.php(153): Flarum\Formatter\Formatter->parse()
#9 vendor/flarum/core/src/Post/CommentPost.php(61): Flarum\Post\CommentPost->setContentAttribute()
#10 vendor/flarum/core/src/Post/Command/PostReplyHandler.php(84): Flarum\Post\CommentPost::reply()
#11 vendor/illuminate/bus/Dispatcher.php(122): Flarum\Post\Command\PostReplyHandler->handle()
#12 vendor/illuminate/pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#13 vendor/illuminate/pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#14 vendor/illuminate/bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#15 vendor/illuminate/bus/Dispatcher.php(78): Illuminate\Bus\Dispatcher->dispatchNow()
#16 vendor/flarum/core/src/Api/Controller/CreatePostController.php(61): Illuminate\Bus\Dispatcher->dispatch()
#17 vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(116): Flarum\Api\Controller\CreatePostController->data()
#18 vendor/flarum/core/src/Api/Controller/AbstractCreateController.php(22): Flarum\Api\Controller\AbstractSerializeController->handle()
#19 vendor/flarum/core/src/Http/RouteHandlerFactory.php(41): Flarum\Api\Controller\AbstractCreateController->handle()
#20 vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#21 vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ExecuteRoute->process()
#22 vendor/malago/flarum-achievements/src/Middlewares/MiddlewarePosted.php(27): Laminas\Stratigility\Next->handle()
#23 vendor/laminas/laminas-stratigility/src/Next.php(49): Malago\Achievements\Middlewares\MiddlewarePosted->process()
#24 vendor/flarum/core/src/Api/Middleware/ThrottleApi.php(33): Laminas\Stratigility\Next->handle()
#25 vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Api\Middleware\ThrottleApi->process()
#26 vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(44): Laminas\Stratigility\Next->handle()
#27 vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\CheckCsrfToken->process()
#28 vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(69): Laminas\Stratigility\Next->handle()
#29 vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ResolveRoute->process()
#30 vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle()
#31 vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\SetLocale->process()
#32 vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(58): Laminas\Stratigility\Next->handle()
#33 vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\AuthenticateWithHeader->process()
#34 vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(31): Laminas\Stratigility\Next->handle()
#35 vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\AuthenticateWithSession->process()
#36 vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Laminas\Stratigility\Next->handle()
#37 vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\RememberFromCookie->process()
#38 vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#39 vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\StartSession->process()
#40 vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Laminas\Stratigility\Next->handle()
#41 vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Api\Middleware\FakeHttpMethods->process()
#42 vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#43 vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ParseJsonBody->process()
#44 vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#45 vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\HandleErrors->process()
#46 vendor/flarum/core/src/Http/Middleware/InjectActorReference.php(25): Laminas\Stratigility\Next->handle()
#47 vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\InjectActorReference->process()
#48 vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#49 vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#50 vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\RequestHandler->process()
#51 vendor/middlewares/base-path-router/src/BasePathRouter.php(99): Laminas\Stratigility\Next->handle()
#52 vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\BasePathRouter->process()
#53 vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(36): Laminas\Stratigility\Next->handle()
#54 vendor/laminas/laminas-stratigility/src/Next.php(49): Laminas\Stratigility\Middleware\OriginalMessages->process()
#55 vendor/middlewares/base-path/src/BasePath.php(73): Laminas\Stratigility\Next->handle()
#56 vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\BasePath->process()
#57 vendor/flarum/core/src/Http/Middleware/ProcessIp.php(24): Laminas\Stratigility\Next->handle()
#58 vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ProcessIp->process()
#59 vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#60 vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(64): Laminas\Stratigility\MiddlewarePipe->process()
#61 vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle()
#62 vendor/flarum/core/src/Http/Server.php(45): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#63 public/index.php(26): Flarum\Http\Server->listen()
#64 {main}
```
https://github.com/flarum/mentions/blame/3b3c103dcac4357ffa1c89b3b45bfaa659148318/src/ConfigureMentions.php#LL127C30-L127C30 is introduced in https://github.com/flarum/mentions/commit/77436bea0ccfd79c7643967667b57e85639dc368 which is a fix to GHSA-22m9-m3ww-53h3

**Comment by JoshyPHP** [comment]
Judging by that backtrace, I guess that `actor` is not set. There should be a `$parser->registeredVars['actor'] = ...;` somewhere, to set that parameter before the filter is executed.

**Comment by JoshyPHP** [comment]
Apparently [the var is already set](https://github.com/flarum/flarum-core/blob/5a0aa485397a66ab47bc5b114f207f790fa2cb97/src/Formatter/Formatter.php#L94-L99). Make sure you're not using an old version of something, especially an old cached version of the parser. Open an issue in the https://github.com/flarum/mentions repository and you can tag me there in case it relates to my side of things.

**Comment by n0099** [comment]
> an old cached version of the parser

Where are they being stored? How can I flush them?

> Open an issue in the [flarum/mentions](https://github.com/flarum/mentions)

But all repo under flarum org already closed issues area

**Comment by n0099** [comment]
After running `php flarum cache:clear`, this error no longer appears.
@SychO9 this step should be mentioned in release notes, or get executed after `composer update` via [`post-update-cmd`](https://getcomposer.org/doc/articles/scripts.md)
