### ISSUE TITLE
2.15: TaskLists plugin broken

### ISSUE THREAD

**Issue by tobyzerner** [s9e/TextFormatter#226]
Since upgrading to 2.15, TextFormatter is broken in Waterhole. Can be fixed by simply disabling the `TaskList` plugin. Error and relevant stacktrace below.

```
[2023-12-07 08:47:42] local.ERROR: Not Found Error {"exception":"[object] (DOMException(code: 8): Not Found Error at /Users/toby/Sites/waterhole/vendor/s9e/sweetdom/src/NodeTraits/MagicMethods.php:44)
[stacktrace]
#0 /Users/toby/Sites/waterhole/vendor/s9e/sweetdom/src/NodeTraits/MagicMethods.php(44): DOMElement->replaceWith(Object(s9e\\SweetDOM\\Element))
#1 /Users/toby/Sites/waterhole/vendor/s9e/sweetdom/src/NodeTraits/PolyfillMethods.php(35): s9e\\SweetDOM\\Element->magicMethodsCall('replaceWithXslC...', Array)
#2 /Users/toby/Sites/waterhole/vendor/s9e/sweetdom/src/NodeTraits/DeprecatedMethods.php(48): s9e\\SweetDOM\\Element->polyfillMethodsCall('replaceWithXslC...', Array)
#3 /Users/toby/Sites/waterhole/vendor/s9e/text-formatter/src/Configurator/TemplateNormalizations/DeoptimizeIf.php(27): s9e\\SweetDOM\\Element->__call('replaceWithXslC...', Array)
#4 /Users/toby/Sites/waterhole/vendor/s9e/text-formatter/src/Configurator/TemplateNormalizations/AbstractNormalization.php(119): s9e\\TextFormatter\\Configurator\\TemplateNormalizations\\DeoptimizeIf->normalizeElement(Object(s9e\\SweetDOM\\Element))
#5 /Users/toby/Sites/waterhole/vendor/s9e/text-formatter/src/Configurator/TemplateNormalizations/AbstractNormalization.php(48): s9e\\TextFormatter\\Configurator\\TemplateNormalizations\\AbstractNormalization->normalizeNode(Object(s9e\\SweetDOM\\Element))
#6 /Users/toby/Sites/waterhole/vendor/s9e/text-formatter/src/Configurator/TemplateNormalizer.php(146): s9e\\TextFormatter\\Configurator\\TemplateNormalizations\\AbstractNormalization->normalize(Object(s9e\\SweetDOM\\Element))
#7 /Users/toby/Sites/waterhole/vendor/s9e/text-formatter/src/Configurator/Items/Template.php(165): s9e\\TextFormatter\\Configurator\\TemplateNormalizer->normalizeTemplate('<input data-tas...')
#8 /Users/toby/Sites/waterhole/vendor/s9e/text-formatter/src/Configurator/TemplateNormalizer.php(124): s9e\\TextFormatter\\Configurator\\Items\\Template->normalize(Object(s9e\\TextFormatter\\Configurator\\TemplateNormalizer))
#9 /Users/toby/Sites/waterhole/vendor/s9e/text-formatter/src/Configurator.php(239): s9e\\TextFormatter\\Configurator\\TemplateNormalizer->normalizeTag(Object(s9e\\TextFormatter\\Configurator\\Items\\Tag))
#10 /Users/toby/Sites/waterhole/packages/core/src/Formatter/Formatter.php(134): s9e\\TextFormatter\\Configurator->finalize()
```

**Comment by cornatul** [comment]
so what's the fix ?
