### ISSUE TITLE
BBcode image mark malformed

### ISSUE THREAD

**Issue by hardware** [s9e/TextFormatter#35]
It's me, again.. :)

I have a problem with images with alt option :

```php
$xml = TextFormatter::parse("[img=myimage]https://i.giphy.com/pWWT4gCzW1V9S.gif[/img]");
$html = TextFormatter::render($xml);

echo $html;
```

Result :

```html
<img alt="" title="" src="myimage"><a rel="nofollow noreferrer" target="_blank" href="https://i.giphy.com/pWWT4gCzW1V9S.gif">https://i.giphy.com/pWWT4gCzW1V9S.gif</a>[/img]
```

Expected :

```html
<img src="https://i.giphy.com/pWWT4gCzW1V9S.gif" alt="myimage">
```

![example](https://s31.postimg.org/oculocoiz/Capture.png)

**Comment by JoshyPHP** [comment]
The default `[IMG]` BBCode's default attribute  is the image's URL. The following forms are equivalent:

    [img]image.png[/img]
    [img=image.png]

If you want the `alt` attribute by default, you'll have to create your own custom BBCode.

```php
$configurator = new s9e\TextFormatter\Configurator;

$configurator->BBCodes->addCustom(
	'[IMG alt={TEXT;optional} src={URL;useContent}]',
	'<img src="{@src}"><xsl:copy-of select="@alt"/></img>'
);

extract($configurator->finalize());

$text = '[img=myimage]https://i.giphy.com/pWWT4gCzW1V9S.gif[/img]';
$xml  = $parser->parse($text);
$html = $renderer->render($xml);

echo $html;
```
```html
<img src="https://i.giphy.com/pWWT4gCzW1V9S.gif" alt="myimage">
```

By the way, is that from FluxBB? I don't recall seeing that syntax in a forum software but if it turns out that a majority of forums support this syntax then I would consider adopting it in the Forum bundle.

**Comment by hardware** [comment]
Yes it's from Fluxbb, I thought it was a standard tag in bbcode language, thank for the example btw.

**Comment by hardware** [comment]
I try your example but I got this error :

```
PHP Fatal error:  Uncaught RuntimeException: BBCode 'IMG' already exists in /scripts/TextFormatter/src/Plugins/BBCodes/Configurator/BBCodeCollection.php:23                        
Stack trace:                                                                                                                                                                       
#0 /scripts/TextFormatter/src/Configurator/Collections/NormalizedCollection.php(131): s9e\TextFormatter\Plugins\BBCodes\Configurator\BBCodeCollection->getAlreadyExistsException('I
MG')                                                                                                                                                                               
#1 /scripts/TextFormatter/src/Plugins/BBCodes/Configurator.php(169): s9e\TextFormatter\Configurator\Collections\NormalizedCollection->add('IMG', Object(s9e\TextFormatter\Plugins\B
BCodes\Configurator\BBCode))                                                                                                                                                       
#2 /scripts/TextFormatter/src/Plugins/BBCodes/Configurator.php(117): s9e\TextFormatter\Plugins\BBCodes\Configurator->addFromConfig(Array)                                          
#3 /scripts/createCustomBundle.php(10): s9e\TextFormatter\Plugins\BBCodes\Configurator->addCustom('[IMG alt={TEXT;...', '<img src="{@src...')                                      
#4 {main}                                                                                                                                                                          
  thrown in /scripts/TextFormatter/src/Plugins/BBCodes/Configurator/BBCodeCollection.php on line 23
```

How i can replace with my custom bbcode rule ?

**Comment by JoshyPHP** [comment]
You can either remove the BBCode/tag before adding your own:
```php
unset($configurator->tags['IMG']);
unset($configurator->BBCodes['IMG']);
```
...or disable the duplicate check:
```php
// Possible values:  "error" (default), "ignore" or "replace"
$configurator->tags->onDuplicate('replace');
$configurator->BBCodes->onDuplicate('replace');
```

The latter might become the default behaviour at some point in the future.

**Comment by hardware** [comment]
Ah, perfect ! You've thought of everything ! :smiley:
